export const USER_FETCH_SUCCEEDED: string = "USER_FETCH_SUCCEEDED";
export const FETCH_USER: string = "FETCH_USER";

export const ADD_USER: string = "ADD_USER";
export const UPDATE_USER_ROLE: string = "UPDATE_USER_ROLE";
export const UPDATE_USER_ROLE_SUCCEEDED: string = "UPDATE_USER_ROLE_SUCCEEDED";

export const AUTHENTICATE_USER: string = "AUTHENTICATE_USER";
export const AUTHENTICATE_USER_ERR: string = "AUTHENTICATE_USER_ERR";
export const AUTHENTICATE_USER_SUCCESS: string = "AUTHENTICATE_USER_SUCCESS";

export const USER_UPDATE_ERROR : string = "USER_UPDATE_ERROR";